### PR TITLE
Add scrollback buffer to readline

### PR DESCRIPTION
**Pull request by ssaundersla**
My approach to a scrollback buffer for the console's readline() method. It looked to me from the commit log like PRs generally go to the master branch, so that's how I've set it up. If you have a different policy, please let me know.

### CODE REVIEW

**Comment by timsneath** [comment]
This is great. Two ideas:

1. This should be optional, since there are certain scenarios (e.g. entering a command in the Kilo editor) where single-line is required. 
1. It would be good to have a sample that demonstrates this. I've not invested in testing yet, but I've been using samples to make sure that the various core features are easily testable. You could modify an existing one. 

WDYT?

**Comment by ssaundersla** [comment]
Thank you for the note about e.g. `kilo` -- it hadn't occurred to me that there would be a use case for the buffer *not* scrolling back. I'll update the PR and add an example as well.

**Comment by timsneath** [comment]
Great - thanks!

**Comment by ssaundersla** [comment]
I pushed an update. Have you had a chance to look?

**Comment by timsneath** [comment]
I saw! Thank you -- I'll take a look over the weekend.

**Pull request merged**
